name: Build Eldessouky Labels EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install pillow
          pip install customtkinter

      - name: Build using .spec (safe mode)
        run: |
          pyinstaller Eldessouky-Labels.spec --clean

      - name: Upload EXE folder
        uses: actions/upload-artifact@v4
        with:
          name: Eldessouky-Labels
          path: dist/Eldessouky-Labels/
